# Generated by Django 4.0.5 on 2024-05-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descricao', models.CharField(max_length=255)),
                ('Tamanho', models.CharField(choices=[('PP', 'PP'), ('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG'), ('EXG', 'EXG'), ('G1', 'G1'), ('G2', 'G2'), ('G3', 'G3')], max_length=4)),
                ('Estoque_entrada', models.CharField(max_length=255)),
                ('Codigo_Produto', models.CharField(max_length=255)),
                ('Preço_Compra', models.CharField(max_length=255)),
                ('Preço_Venda', models.CharField(max_length=255)),
            ],
        ),
    ]
